// @generated automatically by Diesel CLI.

diesel::table! {
    a (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    b (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    c (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    d (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    e (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    f (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    g (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    h (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    i (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    j (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    k (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    l (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    m (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    n (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    o (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    p (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    q (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    r (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    s (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    t (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    u (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    v (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    w (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    x (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    y (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::table! {
    z (id) {
        id -> Int4,
        name -> Nullable<Text>,
        a_id -> Nullable<Int4>,
        b_id -> Nullable<Int4>,
        c_id -> Nullable<Int4>,
        d_id -> Nullable<Int4>,
        e_id -> Nullable<Int4>,
        f_id -> Nullable<Int4>,
        g_id -> Nullable<Int4>,
        h_id -> Nullable<Int4>,
        i_id -> Nullable<Int4>,
        j_id -> Nullable<Int4>,
        k_id -> Nullable<Int4>,
        l_id -> Nullable<Int4>,
        m_id -> Nullable<Int4>,
        n_id -> Nullable<Int4>,
        o_id -> Nullable<Int4>,
        p_id -> Nullable<Int4>,
        q_id -> Nullable<Int4>,
        r_id -> Nullable<Int4>,
        s_id -> Nullable<Int4>,
        t_id -> Nullable<Int4>,
        u_id -> Nullable<Int4>,
        v_id -> Nullable<Int4>,
        w_id -> Nullable<Int4>,
        x_id -> Nullable<Int4>,
        y_id -> Nullable<Int4>,
        z_id -> Nullable<Int4>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,
);
